CTkLabel Warning: Given image is not CTkImage but <class 'tkinter.PhotoImage'>. Image can not be scaled on HighDPI displays, use CTkImage instead.
CTkLabel Warning: Given image is not CTkImage but <class 'tkinter.PhotoImage'>. Image can not be scaled on HighDPI displays, use CTkImage instead.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\madru\OneDrive - Universidad Politécnica de Madrid\Practicum\Scripts para teledeteccion\SatChange\lib\changeDetector.py", line 152, in changeDetectorFile
    changeDetector(img, path, rt, sensivity)
  File "c:\Users\madru\OneDrive - Universidad Politécnica de Madrid\Practicum\Scripts para teledeteccion\SatChange\lib\changeDetector.py", line 132, in changeDetector
    saveSingleBand(out_file, raster, mask, gdal.GDT_Byte, 'GTiff')
  File "c:\Users\madru\OneDrive - Universidad Politécnica de Madrid\Practicum\Scripts para teledeteccion\SatChange\lib\changeDetector.py", line 69, in saveSingleBand
    output.GetRasterBand(1).WriteArray(img)
AttributeError: 'NoneType' object has no attribute 'WriteArray'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\madru\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\customtkinter\windows\widgets\ctk_button.py", line 531, in _clicked
    self._command()
  File "c:\Users\madru\OneDrive - Universidad Politécnica de Madrid\Practicum\Scripts para teledeteccion\SatChange\satchange.py", line 1150, in changedetection
    self.master.update()
  File "C:\Users\madru\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\customtkinter\windows\ctk_tk.py", line 142, in update
    super().update()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1314, in update
    self.tk.call('update')
KeyboardInterrupt
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1889, in __call__
    try:
KeyboardInterrupt
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1889, in __call__
    try:
KeyboardInterrupt
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1889, in __call__
    try:
KeyboardInterrupt
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1889, in __call__
    try:
KeyboardInterrupt
Traceback (most recent call last):
  File "c:\Users\madru\OneDrive - Universidad Politécnica de Madrid\Practicum\Scripts para teledeteccion\SatChange\satchange.py", line 1710, in <module>
    app.mainloop()
  File "C:\Users\madru\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\customtkinter\windows\ctk_tk.py", line 153, in mainloop
    super().mainloop(*args, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1429, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
